# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle for jpacman

on:
  push:
    branches: [ master, eric_githubActions ]
  pull_request:
    branches: [ master, eric_githubActions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Install xvfb
      run: sudo apt-get install xvfb
      working-directory: jpacman
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: jpacman
    - name: xvfb build with gradle
      uses: GabrielBB/xvfb-action@v1
      with:
        run: gradlew build
        working-directory: jpacman
    - name: xvfb gradle test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: gradlew test jacocoTestReport
        working-directory: jpacman    
    - name: xvfb gradle static analysis
      uses: GabrielBB/xvfb-action@v1
      with:
        run: gradlew staticAnalysis
        working-directory: jpacman
